AllCops:
  Include:
    - ./**/*.rb
  Exclude:
    - vendor/**/*
    - pkg/**/*
    - spec/fixtures/**/*
    - '**/Gemfile'
    - '**/Rakefile'

# Configuration parameters: AllowURI, URISchemes.
Metrics/LineLength:
  Max: 328
Metrics/BlockLength:
  Max: 150

# 'Complexity' is very relative
Metrics/PerceivedComplexity:
  Enabled: false

# 'Complexity' is very relative
Metrics/CyclomaticComplexity:
  Enabled: false

# 'Complexity' is very relative
Metrics/AbcSize:
  Enabled: false

# Method length is not necessarily an indicator of code quality
Metrics/MethodLength:
  Enabled: false

# Class length is not necessarily an indicator of code quality
Metrics/ClassLength:
  Enabled: false

Lint/ScriptPermission:
  Description: 'Grant script file execute permission.'
  Enabled: false

Style/PercentLiteralDelimiters:
  Description: "Use `%`-literal delimiters consistently"
  Enabled: true
  PreferredDelimiters:
    "%i": "[]"
    "%r": "{}"
    "%w": "[]"
    "%W": "[]"
    "%x": "[]"

Style/WordArray:
  Description: "Use %w or %W for arrays of words."
  Enabled: true

# dealbreaker:
Style/TrailingCommaInArguments:
  Enabled: false
Style/TrailingCommaInArrayLiteral:
  Enabled: false
Layout/ClosingParenthesisIndentation:
  Enabled: false

# we still support ruby 1.8
Style/HashSyntax:
  Enabled: false

Lint/AmbiguousRegexpLiteral:
  Enabled: true
Style/RegexpLiteral:
  Enabled: false

# this catches the cases of using `module` for parser functions, types, or
# providers
Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Description: 'Document classes and non-namespace modules.'
  Enabled: false

# More comfortable block layouts
Style/BlockDelimiters:
  Enabled: False

Layout/MultilineBlockLayout:
  Enabled: False

Lint/ReturnInVoidContext:
  Exclude:
    - spec/*
